FROM openjdk:8u191-jre-alpine3.8
RUN apk add curl jq
WORKDIR /Users/macbook/IdeaProjects/DiplomaProject
COPY target/OpenWeatherJava-1.0-SNAPSHOT.jar OpenWeatherJava-1.0-SNAPSHOT.jar
COPY target/OpenWeatherJava-1.0-SNAPSHOT-tests.jar OpenWeatherJava-1.0-SNAPSHOT-tests.jar
COPY target/libs libs
COPY testng.xml testng.xml
#ENTRYPOINT java -cp OpenWeatherJava-1.0-SNAPSHOT.jar:OpenWeatherJava-1.0-SNAPSHOT-tests.jar:libs/* -DBROWSER=$BROWSER -DHUB_HOST=$HUB_HOST org.testng.TestNG $MODULE
#Add healthcheck.sh healthcheck.sh
RUN wget https://s3.amazonaws.com/selenium-docker/healthcheck/healthcheck.sh
ENTRYPOINT sh healthcheck.sh
